version: '3.3'

volumes:
  data_foodgram:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - data_foodgram:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: foodgram/Dockerfile
    env_file: ../.env
    depends_on:
      db:
        condition: service_started
    volumes:
      - static:/backend_static
      - media:/app/foodgram/media
      - ../data:/app/data/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully
    volumes:
      - static:/staticfiles
      - media:/app/foodgram/media
