version: '3.3'

volumes:
  foodgram_data:
  static:
  media:

services:

  db:
    image: postgres:15.4
    env_file: .env
    volumes:
      - foodgram_data:/var/lib/postgresql/data

  backend:
    image: mign0n/backend_foodgram
    env_file: .env
    depends_on:
      db:
        condition: service_started
    volumes:
      - static:/backend_static
      - media:/app/foodgram/media
      - ./data:/app/data/

  frontend:
    image: mign0n/frontend_foodgram
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: mign0n/gateway_foodgram
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully
    volumes:
      - static:/staticfiles
      - media:/app/foodgram/media
